package planit.people.preparation.Entities;

import javax.persistence.*;

/**
 * this class is used to represent the Table Person in the DB.
 * getter methods are set for all attributes but 'person_id' since it is not used.
 */
@Entity
@Table(name = "Person")
public class Entity_Person {
    /**
     * primary key of the table, it is autogenerated.
     * the attribute is used in a json body with the name "person_id"
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "person_gen")
    @SequenceGenerator(name = "person_gen", sequenceName = "person_seq", allocationSize = 1)
    @Column(name = "person_id", nullable = false)
    private Long person_id;
    /**
     * defines the gender of the person
     */
    @Column(name = "gender", length = 80)
    private String gender;
    /**
     * defines the first name of the person
     */
    @Column(name = "name")
    private String name;
    /**
     * defines the surname of the person
     */
    @Column(name = "surname")
    private String surname;
    /**
     * defines the age of the person
     */
    @Column(name = "age")
    private Integer age;


    public Entity_Person() {

    }

    /**
     * constructor used to create a new person, the id is autogenerated.
     *
     * @param gender  person gender
     * @param name    person first name
     * @param surname person surname
     * @param age     person age
     */
    public Entity_Person(String gender, String name, String surname, Integer age) {
        this.gender = gender;
        this.name = name;
        this.surname = surname;
        this.age = age;
    }

    /**
     * Constructor used to return the person object from DB
     * @param person_id person Id in the DB
     * @param gender  person gender
     * @param name    person first name
     * @param surname person surname
     * @param age     person age
     */
    public Entity_Person(Long person_id, String gender, String name, String surname, Integer age) {
        this.person_id = person_id;
        this.gender = gender;
        this.name = name;
        this.surname = surname;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public String getSurname() {
        return surname;
    }

    public String getGender() {
        return gender;
    }

    public Integer getAge() {
        return age;
    }

    public Long getPerson_id() {
        return person_id;
    }

    @Override
    public String toString() {
        return "Entity_Person{" +
                "person_id=" + person_id +
                ", gender='" + gender + '\'' +
                ", name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", age=" + age +
                '}';
    }
}
