package planit.people.preparation.Entities;

import javax.persistence.*;

@Entity
@Table(name = "planit_user")
public class Entity_User {
    /**
     * primary key of the table, it is autogenerated.
     * the attribute is used in a json body with the name "person_id"
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_gen")
    @SequenceGenerator(name = "user_gen", sequenceName = "user_seq", allocationSize = 1)
    @Column(name = "planit_user_id", nullable = false)
    private Long user_id;
    /**
     * defines the first name of the person
     */
    @Column(name = "name")
    private String name;
    /**
     * defines the surname of the person
     */
    @Column(name = "surname")
    private String surname;

    /**
     * defines the age of the person
     */


    public Entity_User() {

    }

    /**
     * constructor used to create a new person, the id is autogenerated.
     *
     * @param name    person first name
     * @param surname person surname
     */
    public Entity_User(String name, String surname) {
        this.name = name;
        this.surname = surname;
    }

    /**
     * Constructor used to return the person object from DB
     *
     * @param user_id person Id in the DB
     * @param name    person first name
     * @param surname person surname
     */
    public Entity_User(Long user_id, String name, String surname) {
        this.user_id = user_id;
        this.name = name;
        this.surname = surname;
    }

    public Entity_User(Long user_id) {
        this.user_id = user_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public Long getUser_id() {
        return user_id;
    }

    @Override
    public String toString() {
        return "Entity_User{" +
                "user_id=" + user_id +
                ", name='" + name + '\'' +
                ", surname='" + surname +
                '}';
    }
}
