# include common properties for every profile in this section

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planit
    username: postgres
    password: postgres
  jpa:
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
integrations:
  google-token-redirect-uri: http://localhost:3000

---
# profile specific properties

spring:
  profiles: production
integrations:
  google-token-redirect-uri: https://planit-custom-domain.loca.lt/
